openapi: 3.0.0
servers:
  - description: Local Notty Server
    url: http://127.0.0.1:7779/api/v1

info:
  description: Notty 通知回调服务 API
  version: 1.0.0
  title: Notty 通知回调服务
  contact:
    email: kevinz@weghst.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: tasks
    description: 回调任务

paths:
  /tasks:
    post:
      summary: 提交新的通知任务
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service_name:
                  type: string
                  description: 调用的服务名称
                sid:
                  type: string
                  description: 业务方ID，用于追踪通知任务状态
                cb_url:
                  type: string
                  description: 回调URL
                cb_method:
                  type: string
                  description: 回调方法
                  default: POST
                  enum:
                    - GET
                    - POST
                cb_content_type:
                  type: string
                  description: 回调的 content-type
                  default: application/json; charset=utf-8
                cb_data:
                  type: object
                  description: 回调的请求数据
                cb_delay:
                  type: integer
                  description: 首次回调延迟时间（秒）
                retry_max_count:
                  type: integer
                  description: 重试回调的最大次数
                  default: 99
                  maximum: 999
              example:
                service_name: hello
                sid: 5d41402abc4b2a76b9719d911017c592
                cb_url: https://cb.task/
                cb_method: POST
                cb_data:
                  field1: first
                  field2: second
              required:
                - service_name
                - sid
                - cb_url
                - cb_method
      responses:
        200:
          description: 成功返回任务ID
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    description: 任务ID
                    example: 201807315d41402abc4b2a76b9719d911017c592
                required:
                  - id
    get:
      summary: 任务列表
      tags:
        - tasks
      parameters:
        - in: query
          name: q
          description: 搜索关键字
          schema:
            type: string
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/SizeQuery'
      responses:
        200:
          description: 任务列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskRes'
  /tasks/{id}:
    delete:
      summary: 取消任务通知
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          description: 任务ID
          required: true
          schema:
            type: string
      responses:
        204:
          description: No Content
    get:
      summary: 获取任务信息
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          description: 任务ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 任务详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRes'
  /tasks/{id}/logs:
    get:
      summary: 获取任务回调日志记录
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          description: 任务ID
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/SizeQuery'
      responses:
        200:
          description: 回调日志
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: 回调日志ID
                    n:
                      type: integer
                      description: 已回调次数
                      example: 1
                    http_res_status:
                      type: integer
                      description: 回调响应的 HTTP 状态码
                      example: 200
                    http_res_headers:
                      type: string
                      description: 回调响应的 HTTP 头信息
                    http_res_body:
                      type: string
                      description: 回调响应的 HTTP 主体信息
                    success:
                      type: boolean
                      description: 回调是否成功
                      default: false
                    reason:
                      type: string
                      description: 回调失败原因
                    created_at:
                      type: string
                      description: 回调时间
                      example: "2018-10-15T17:59:57"
                  required:
                    - n
                    - http_res_status
                    - http_res_headers
                    - http_res_body
                    - created_at
components:
  parameters:
    PageQuery:
      in: query
      name: page
      description: 页码
      required: true
      default: 1
      schema:
        type: integer
    SizeQuery:
      in: query
      name: size
      description: 记录数
      required: true
      default: 30
      schema:
        type: integer
  schemas:
    ErrorRes:
      properties:
        code:
          type: integer
          description: 业务错误码
        message:
          type: string
          description: 错误描述
      required:
        - code
        - message
    TaskRes:
      properties:
        id:
          type: string
          description: 任务ID
        service_name:
          type: string
          description: 提交任务的服务名称
        cb_url:
          type: string
          description: 回调URL
        cb_method:
          type: string
          description: 回调方法
          enum:
            - GET
            - POST
        retry_count:
          type: integer
          description: 已重试次数
        retry_max_count:
          type: integer
          description: 最大重试次数
        status:
          type: string
          description: 任务状态
        last_call_at:
          type: integer
          format: int64
          description: 上次回调时间戳
        created_at:
          type: integer
          format: int64
          description: 回调任务创建时间戳